# Generated by Django 4.1.4 on 2023-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bankdetails_servicesdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesdetails',
            name='service_type',
        ),
        migrations.AddField(
            model_name='barberdetails',
            name='service_type',
            field=models.CharField(choices=[('barbershop', 'barbershop'), ('hair_salon', 'hair_salon'), ('beauty_salon', 'beauty_salon'), ('full_service_salon', 'full_service_salon'), ('other', 'other')], default='barbershop', max_length=60),
            preserve_default=False,
        ),
    ]
