# Generated by Django 4.1.4 on 2023-03-19 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0008_ratingsandreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsandreviews',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
